[build]
  command = "pip install -r requirements.txt && python setup_nltk.py"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200